# Generated by Django 4.2.3 on 2023-07-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=50)),
                ('genus', models.CharField(max_length=20)),
                ('species', models.CharField(max_length=20)),
                ('plant_type', models.CharField(max_length=50)),
                ('country_of_origin', models.CharField(max_length=20)),
                ('conservation_status', models.BooleanField()),
            ],
        ),
    ]
