# Generated by Django 4.2.3 on 2023-07-27 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='conservation_status',
            new_name='endangered',
        ),
    ]
